version: '3.2'

services:
  pg_srv:
    image: postgres
    container_name: 'postgres'
    restart: always
    ports:
      - 5432:5432
      - 5433:5433
    environment: 
      POSTGRES_PASSWORD: moloko
      POSTGRES_USER: moloko
      POSTGRES_DB: moloko
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: 'adminer'
    restart: always
    ports:
      - 8080:8080
  
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
  

